### ISSUE TITLE
peer review!

### ISSUE THREAD

**Issue by cristinaasu** [SameeckBhatia/Seattle-Real-Estate#4]
R/Python cited (1/1 pts)
Data cited (1/1 pts)
Class paper (1/1 pts)
LLM documentation (1/1 pts)
Title (2/2 pts)
Author, date, and repo (2/2 pts)
Abstract (0/4 pts)
Introduction (4/4 pts)
Estimand (1/1 pts)
Data (10/10 pts)
Measurement (4/4 pts)
Model (10/10 pts)
Results (10/10 pts)
Discussion (0/10 pts)
Prose (6/6 pts)
Cross-references (1/1 pts)
Captions (2/2 pts)

Graphs/tables/etc (4/4 pts)
i remember the prof saying he doesnt like boxplots but if this is the only to present figure 6 then it should be fine.
 
Surveys, sampling, and observational data appendix (0/10 pts)

Referencing (4/4 pts)
i think this is fine but just rmb to cite other things if u have missed it.

Commits (2/2 pts)
Sketches (2/2 pts)
Simulation (4/4 pts)
Tests (4/4 pts)
Parquet (1/1 pts)
Reproducible workflow (4/4 pts)

Enhancements (0/4 pts)
include ur datasheet under others folder.

Miscellaneous (3/3 pts)

i briefly went through it but overall, pretty good + if u have time you can maybe rename your variables ie. property_age -> Property Price.

**Comment by SameeckBhatia** [comment]
Thank you so much!
